name: Delete merged branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-merged-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_POS }}
          REPO: ${{ github.repository }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          echo "Rama mergeada: $BRANCH_NAME"
          
          if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "dev" ]]; then
            echo "No se puede eliminar la rama principal ($BRANCH_NAME)."
            exit 0
          fi

          curl -X DELETE \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/git/refs/heads/$BRANCH_NAME